pipeline {
   agent any
   stages {
       stage('Install') {
           steps {
            '''
            npm install
            '''
           }
       }
       stage('Delete') {
           steps {
            '''
            pm2 delete all
            '''
           }
       }
       stage('Run') {
           steps {'''
            pm2 start "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" -- start
            '''
           }
       }
   }
}